import { LanguageProvider } from "@/Context/LanguageContext";
import HtmlWrapper from "@/Components/HtmlWrapper"; // new file
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Script from "next/script";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "PlutoSec",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LanguageProvider>
      <HtmlWrapper>
        <head>
          <Script
            type="module"
            src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
            strategy="afterInteractive"
          />
        </head>
        <body>
          <div className="bg-wrapper">
            <div className="circle-container">
              <div className="circle"></div>
              <div className="circle"></div>
            </div>
            <div className="content">
              <Header />
              {children}
              <Footer />
            </div>
          </div>
        </body>
      </HtmlWrapper>
    </LanguageProvider>
  );
}
