import Header from "@/Components/Header";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // add weights you want
  variable: "--font-montserrat", // optional: use as CSS variable
});

export const metadata = {
  title: "PlutoSec",
  description: "Generated by create next app",
};
import Script from "next/script";
import Footer from "@/Components/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          type="module"
          src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
          strategy="afterInteractive"
        />
      </head>
      <body>
        <div className="bg-wrapper">
          <div className="circle-container">
            <div className="circle"></div>
            <div className="circle"></div>
          </div>

          <div className="content">
            <Header />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
